language: python

stages:
  - lint
  - test

jobs:
  include:
  - stage: Lint
    name: "Style check"
    python: "3.8"
    script: flake8 --statistics
  - stage: Test
    name: "Unittest - Python 3.6"
    python: "3.6"
    script: pytest -vv --cov eviex tests/
  - name: "Unittest - Python 3.7"
    python: "3.7"
    script: pytest -vv --cov eviex tests/
  - name: "Unittest - Python 3.8"
    python: "3.8"
    script: pytest -vv --cov eviex tests/
    
before_install:
  - pip install poetry
install:
  - poetry install
